syntax = "proto3";
package fluxService;
option go_package = "./proto/pb";

import "google/protobuf/timestamp.proto";


service fluxService {

    rpc Write(stream Batch) returns (stream Ack);

    rpc QueryRange(QueryRangeRequest) returns (QueryRangeResponse);


}

message Label {

    string name = 1;
    string value = 2;


}

message Sample {

    google.protobuf.Timestamp timestamp =1 ;
    google.protobuf.Timestamp value = 2 ;
}

message Series{

    string metrics = 1;
    repeated Label labels = 2;

}


message Batch {

    string request_id = 1;
    Series series = 2;
    repeated Sample samples = 3;
}

message Ack {
    string request_id = 1;

    uint32 accepted_count = 2;

    string message = 3;
}

message QueryRangeRequest {

    string metric = 1;
    google.protobuf.Timestamp start = 2;
    google.protobuf.Timestamp end = 3;
    
}

message QueryRangeResponse {
    repeated Batch batches = 1;
}