// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/fluxts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_proto_fluxts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fluxts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_proto_fluxts_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_proto_fluxts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fluxts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_proto_fluxts_proto_rawDescGZIP(), []int{1}
}

func (x *Sample) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Sample) GetValue() *timestamppb.Timestamp {
	if x != nil {
		return x.Value
	}
	return nil
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       string                 `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Labels        []*Label               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_proto_fluxts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fluxts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_proto_fluxts_proto_rawDescGZIP(), []int{2}
}

func (x *Series) GetMetrics() string {
	if x != nil {
		return x.Metrics
	}
	return ""
}

func (x *Series) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Series        *Series                `protobuf:"bytes,2,opt,name=series,proto3" json:"series,omitempty"`
	Samples       []*Sample              `protobuf:"bytes,3,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_fluxts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fluxts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_fluxts_proto_rawDescGZIP(), []int{3}
}

func (x *Batch) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Batch) GetSeries() *Series {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *Batch) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AcceptedCount uint32                 `protobuf:"varint,2,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_fluxts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fluxts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_fluxts_proto_rawDescGZIP(), []int{4}
}

func (x *Ack) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Ack) GetAcceptedCount() uint32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRangeRequest) Reset() {
	*x = QueryRangeRequest{}
	mi := &file_proto_fluxts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeRequest) ProtoMessage() {}

func (x *QueryRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fluxts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeRequest.ProtoReflect.Descriptor instead.
func (*QueryRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_fluxts_proto_rawDescGZIP(), []int{5}
}

func (x *QueryRangeRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *QueryRangeRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *QueryRangeRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type QueryRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batches       []*Batch               `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRangeResponse) Reset() {
	*x = QueryRangeResponse{}
	mi := &file_proto_fluxts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeResponse) ProtoMessage() {}

func (x *QueryRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fluxts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeResponse.ProtoReflect.Descriptor instead.
func (*QueryRangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_fluxts_proto_rawDescGZIP(), []int{6}
}

func (x *QueryRangeResponse) GetBatches() []*Batch {
	if x != nil {
		return x.Batches
	}
	return nil
}

var File_proto_fluxts_proto protoreflect.FileDescriptor

const file_proto_fluxts_proto_rawDesc = "" +
	"\n" +
	"\x12proto/fluxts.proto\x12\vfluxService\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\x05Label\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"t\n" +
	"\x06Sample\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value\"N\n" +
	"\x06Series\x12\x18\n" +
	"\ametrics\x18\x01 \x01(\tR\ametrics\x12*\n" +
	"\x06labels\x18\x02 \x03(\v2\x12.fluxService.LabelR\x06labels\"\x82\x01\n" +
	"\x05Batch\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x06series\x18\x02 \x01(\v2\x13.fluxService.SeriesR\x06series\x12-\n" +
	"\asamples\x18\x03 \x03(\v2\x13.fluxService.SampleR\asamples\"e\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0eaccepted_count\x18\x02 \x01(\rR\racceptedCount\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8b\x01\n" +
	"\x11QueryRangeRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"B\n" +
	"\x12QueryRangeResponse\x12,\n" +
	"\abatches\x18\x01 \x03(\v2\x12.fluxService.BatchR\abatches2\x8f\x01\n" +
	"\vfluxService\x121\n" +
	"\x05Write\x12\x12.fluxService.Batch\x1a\x10.fluxService.Ack(\x010\x01\x12M\n" +
	"\n" +
	"QueryRange\x12\x1e.fluxService.QueryRangeRequest\x1a\x1f.fluxService.QueryRangeResponseB\fZ\n" +
	"./proto/pbb\x06proto3"

var (
	file_proto_fluxts_proto_rawDescOnce sync.Once
	file_proto_fluxts_proto_rawDescData []byte
)

func file_proto_fluxts_proto_rawDescGZIP() []byte {
	file_proto_fluxts_proto_rawDescOnce.Do(func() {
		file_proto_fluxts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fluxts_proto_rawDesc), len(file_proto_fluxts_proto_rawDesc)))
	})
	return file_proto_fluxts_proto_rawDescData
}

var file_proto_fluxts_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_fluxts_proto_goTypes = []any{
	(*Label)(nil),                 // 0: fluxService.Label
	(*Sample)(nil),                // 1: fluxService.Sample
	(*Series)(nil),                // 2: fluxService.Series
	(*Batch)(nil),                 // 3: fluxService.Batch
	(*Ack)(nil),                   // 4: fluxService.Ack
	(*QueryRangeRequest)(nil),     // 5: fluxService.QueryRangeRequest
	(*QueryRangeResponse)(nil),    // 6: fluxService.QueryRangeResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_fluxts_proto_depIdxs = []int32{
	7,  // 0: fluxService.Sample.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 1: fluxService.Sample.value:type_name -> google.protobuf.Timestamp
	0,  // 2: fluxService.Series.labels:type_name -> fluxService.Label
	2,  // 3: fluxService.Batch.series:type_name -> fluxService.Series
	1,  // 4: fluxService.Batch.samples:type_name -> fluxService.Sample
	7,  // 5: fluxService.QueryRangeRequest.start:type_name -> google.protobuf.Timestamp
	7,  // 6: fluxService.QueryRangeRequest.end:type_name -> google.protobuf.Timestamp
	3,  // 7: fluxService.QueryRangeResponse.batches:type_name -> fluxService.Batch
	3,  // 8: fluxService.fluxService.Write:input_type -> fluxService.Batch
	5,  // 9: fluxService.fluxService.QueryRange:input_type -> fluxService.QueryRangeRequest
	4,  // 10: fluxService.fluxService.Write:output_type -> fluxService.Ack
	6,  // 11: fluxService.fluxService.QueryRange:output_type -> fluxService.QueryRangeResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_fluxts_proto_init() }
func file_proto_fluxts_proto_init() {
	if File_proto_fluxts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fluxts_proto_rawDesc), len(file_proto_fluxts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fluxts_proto_goTypes,
		DependencyIndexes: file_proto_fluxts_proto_depIdxs,
		MessageInfos:      file_proto_fluxts_proto_msgTypes,
	}.Build()
	File_proto_fluxts_proto = out.File
	file_proto_fluxts_proto_goTypes = nil
	file_proto_fluxts_proto_depIdxs = nil
}
