// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/fluxts.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FluxService_Write_FullMethodName      = "/fluxService.fluxService/Write"
	FluxService_QueryRange_FullMethodName = "/fluxService.fluxService/QueryRange"
)

// FluxServiceClient is the client API for FluxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FluxServiceClient interface {
	Write(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Batch, Ack], error)
	QueryRange(ctx context.Context, in *QueryRangeRequest, opts ...grpc.CallOption) (*QueryRangeResponse, error)
}

type fluxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFluxServiceClient(cc grpc.ClientConnInterface) FluxServiceClient {
	return &fluxServiceClient{cc}
}

func (c *fluxServiceClient) Write(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Batch, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FluxService_ServiceDesc.Streams[0], FluxService_Write_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Batch, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FluxService_WriteClient = grpc.BidiStreamingClient[Batch, Ack]

func (c *fluxServiceClient) QueryRange(ctx context.Context, in *QueryRangeRequest, opts ...grpc.CallOption) (*QueryRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRangeResponse)
	err := c.cc.Invoke(ctx, FluxService_QueryRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FluxServiceServer is the server API for FluxService service.
// All implementations must embed UnimplementedFluxServiceServer
// for forward compatibility.
type FluxServiceServer interface {
	Write(grpc.BidiStreamingServer[Batch, Ack]) error
	QueryRange(context.Context, *QueryRangeRequest) (*QueryRangeResponse, error)
	mustEmbedUnimplementedFluxServiceServer()
}

// UnimplementedFluxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFluxServiceServer struct{}

func (UnimplementedFluxServiceServer) Write(grpc.BidiStreamingServer[Batch, Ack]) error {
	return status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedFluxServiceServer) QueryRange(context.Context, *QueryRangeRequest) (*QueryRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRange not implemented")
}
func (UnimplementedFluxServiceServer) mustEmbedUnimplementedFluxServiceServer() {}
func (UnimplementedFluxServiceServer) testEmbeddedByValue()                     {}

// UnsafeFluxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FluxServiceServer will
// result in compilation errors.
type UnsafeFluxServiceServer interface {
	mustEmbedUnimplementedFluxServiceServer()
}

func RegisterFluxServiceServer(s grpc.ServiceRegistrar, srv FluxServiceServer) {
	// If the following call panics, it indicates UnimplementedFluxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FluxService_ServiceDesc, srv)
}

func _FluxService_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FluxServiceServer).Write(&grpc.GenericServerStream[Batch, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FluxService_WriteServer = grpc.BidiStreamingServer[Batch, Ack]

func _FluxService_QueryRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxServiceServer).QueryRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FluxService_QueryRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxServiceServer).QueryRange(ctx, req.(*QueryRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FluxService_ServiceDesc is the grpc.ServiceDesc for FluxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FluxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fluxService.fluxService",
	HandlerType: (*FluxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryRange",
			Handler:    _FluxService_QueryRange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _FluxService_Write_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/fluxts.proto",
}
